### ISSUE TITLE
Android: random crashes

### ISSUE THREAD

**Issue by ortexx** [ghenry22/cordova-plugin-music-controls2#41]
Android 10

I get my app crashed from time to time with errors:

```
10-26 06:33:30.516 11500 23961 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-24
10-26 06:33:30.516 11500 23961 E AndroidRuntime: Process: com.museria.musiphone, PID: 11500
10-26 06:33:30.516 11500 23961 E AndroidRuntime: java.lang.IllegalArgumentException: Duplicate key in ArrayMap: null
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2078)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2042)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1990)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2776)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:497)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:447)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:423)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:75)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControls$2.run(MusicControls.java:149)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.util.ArrayMap.validate(ArrayMap.java:672)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3259)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
10-26 06:33:30.516 11500 23961 E AndroidRuntime: 	at android.os.Bundle.getParcelable(Bundle.java:951)
```
or

```
10-24 17:48:11.555 27921 28882 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-8
10-24 17:48:11.555 27921 28882 E AndroidRuntime: Process: com.museria.musiphone, PID: 27921
10-24 17:48:11.555 27921 28882 E AndroidRuntime: java.util.ConcurrentModificationException
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at android.util.ArrayMap.put(ArrayMap.java:583)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at android.os.Bundle.putParcelable(Bundle.java:507)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at android.app.Notification.addFieldsFromContext(Notification.java:2987)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at android.app.Notification.addFieldsFromContext(Notification.java:2980)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at android.app.Notification$Builder.build(Notification.java:5894)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:74)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControls$2.run(MusicControls.java:149)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-24 17:48:11.555 27921 28882 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

or

```
10-24 14:10:12.936 20170 14568 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-48
10-24 14:10:12.936 20170 14568 E AndroidRuntime: Process: com.museria.musiphone, PID: 20170
10-24 14:10:12.936 20170 14568 E AndroidRuntime: java.lang.IllegalStateException: finishBroadcast() called outside of a broadcast
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at android.os.RemoteCallbackList.finishBroadcast(RemoteCallbackList.java:320)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setPlaybackState(MediaSessionCompat.java:3464)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at android.support.v4.media.session.MediaSessionCompat.setPlaybackState(MediaSessionCompat.java:715)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControls.setMediaPlaybackState(MusicControls.java:237)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControls.access$300(MusicControls.java:42)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at com.homerours.musiccontrols.MusicControls$2.run(MusicControls.java:168)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-24 14:10:12.936 20170 14568 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

What can be the reason?

**Comment by ortexx** [comment]
I found it out.

**Comment by nsolter** [comment]
@ortexx what was the issue? I'm seeing this too.

**Comment by ortexx** [comment]
MusicControls.create() is async. You have to be sure that you don't call it more than once until it is resolved.

That function can take callback if necessary.

**Comment by nsolter** [comment]
> MusicControls.create() is async. You have to be sure that you don't call it more than once until it is resolved.
> 
> That function can take callback if necessary.

Thanks for the quick reply
